"""
contextual_retrieval/models.py

Pydantic data models for Anthropic-style contextual retrieval.
"""
from __future__ import annotations

from typing import Optional
from pydantic import BaseModel, Field


class ContextualChunk(BaseModel):
    """
    A chunk enriched with Anthropic-style contextual information.
    The embedding_text field (context + content) is what gets embedded
    into Qdrant instead of raw chunk content alone.
    """
    chunk_id: int = Field(description="Unique chunk identifier")
    paper_id: str = Field(description="arXiv ID of the source paper")
    arxiv_id: str = Field(description="arXiv ID (alias for paper_id)")
    title: str = Field(default="", description="Paper title")
    context: str = Field(
        description="2-4 sentence retrieval context generated by LLM"
    )
    content: str = Field(description="Raw chunk text")
    embedding_text: str = Field(
        description="context + content — this is what gets embedded"
    )
    chunk_index: int = Field(default=0)
    published: str = Field(default="")
    context_source: str = Field(
        default="llm",
        description="'llm' if context was LLM-generated, 'fallback' if abstract-only"
    )


class ContextBatch(BaseModel):
    """Batch of chunks to be contextualized together."""
    paper_id: str
    title: str
    summary: str
    chunks: list[dict]

    model_config = {"arbitrary_types_allowed": True}


class ContextGenerationResult(BaseModel):
    """Result of a single chunk context generation."""
    chunk_id: int
    context: str
    success: bool = True
    error: Optional[str] = None
